---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/qartaonl/public_html/gisnet
    - echo "Starting deployment..."
    - /bin/cp -R * $DEPLOYPATH
    - echo "Deployment complete."

pre_deploy:
  tasks:
    - echo "Preparing for deployment..."
    - git checkout main
    - git pull origin main

cron:
  tasks:
    - description: "Auto-deploy from GitHub when changes are detected"
      command: "/usr/local/cpanel/bin/cpapi2 VersionControl deployuserrepo repository=gisnet branch=main"
      schedule: "*/5 * * * *"
      enabled: 1