---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/qartaonl/public_html/gisnet
    - echo "Starting deployment..."
    - /bin/cp -R * $DEPLOYPATH
    - echo "Deployment complete."
    
pre_deploy:
  tasks:
    - echo "Preparing for deployment..."
    - git fetch origin main
    - git checkout main
    - git pull origin main